# Generated by Django 4.2.7 on 2023-11-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="diagnosisPatient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("doctorname", models.CharField(max_length=255, null=True)),
                ("patientid", models.CharField(max_length=30, null=True)),
                ("patientName", models.CharField(max_length=255, null=True)),
                (
                    "diagnosisTime",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("returntime", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "diagnosis",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("patientName", models.CharField(max_length=255)),
                ("patientSex", models.CharField(max_length=30)),
                ("patientAge", models.CharField(max_length=30)),
                ("patientWeight", models.CharField(max_length=30)),
                ("date", models.CharField(max_length=30)),
                ("report", models.CharField(max_length=255)),
                ("doctor", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "patients",
            },
        ),
    ]
