# Generated by Django 4.2.7 on 2023-11-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientsManage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosispatient",
            name="Pics",
            field=models.ImageField(blank=True, null=True, upload_to="DPics/"),
        ),
        migrations.AddField(
            model_name="patient",
            name="patientPic",
            field=models.ImageField(blank=True, null=True, upload_to="Pics/"),
        ),
    ]
