# Generated by Django 4.2.7 on 2023-11-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "patientsManage",
            "0003_remove_diagnosispatient_pics_diagnosispatient_pic_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="report",
            field=models.TextField(null=True),
        ),
    ]
