# Generated by Django 4.2.7 on 2023-12-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientsManage", "0004_alter_patient_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="complaint",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("patient_id", models.CharField(max_length=30, null=True)),
                ("patient_name", models.CharField(max_length=255)),
                (
                    "complaint_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("contents", models.TextField(null=True)),
                ("reply", models.TextField(null=True)),
                ("results", models.TextField(null=True)),
            ],
            options={
                "db_table": "complaint",
            },
        ),
        migrations.CreateModel(
            name="duty",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.CharField(blank=True, max_length=100, null=True)),
                ("arrange", models.CharField(max_length=255)),
                ("doctor_id", models.CharField(max_length=30, null=True)),
                ("realname", models.CharField(db_index=True, max_length=30)),
                ("gender", models.CharField(max_length=30)),
                ("telephone", models.CharField(max_length=30)),
                ("attendance", models.CharField(max_length=30)),
                ("response", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "duty",
            },
        ),
        migrations.CreateModel(
            name="flow",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("doctor_id", models.CharField(max_length=30, null=True)),
                ("realname", models.CharField(db_index=True, max_length=30)),
                ("hiredate", models.CharField(blank=True, max_length=100, null=True)),
                ("resigndate", models.CharField(max_length=200)),
                ("reason", models.TextField(null=True)),
            ],
            options={
                "db_table": "flow",
            },
        ),
    ]
