# Generated by Django 4.2.7 on 2023-11-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booksManage", "0002_readbook"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("patientName", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=30)),
                ("patientSex", models.CharField(max_length=30)),
                ("patientAge", models.CharField(max_length=30)),
                ("patientWeight", models.CharField(max_length=30)),
                ("report", models.CharField(max_length=255)),
                ("doctor", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "patients",
            },
        ),
        migrations.DeleteModel(
            name="Books",
        ),
    ]
